apiVersion: v1
kind: Namespace
metadata:
  name: apps-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: directus
---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: v1
kind: Namespace
metadata:
  name: escape
---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo
---
apiVersion: v1
kind: Namespace
metadata:
  name: forge-platform
