apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lucas-engineering-apps
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/lward27/lucas_engineering.git
